name: Daily News Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          # --- 这里必须把 Secrets 传给环境变量 ---
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}  # <--- 新增这一行！
        run: python main.py
